# Generated by Django 4.2.24 on 2025-10-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
